const tasks = [
  {
    id: 1,
    title: "Complete React project",
    description: "Finish the task management UI for the application.",
    priority: "high",
    dueDate: "2024-11-20",
    completed: false,
    category: "Work",
  },
  {
    id: 2,
    title: "Grocery Shopping",
    description: "Buy vegetables, milk, and bread.",
    priority: "medium",
    dueDate: "2024-11-15",
    completed: true,
    category: "Personal",
  },
  {
    id: 3,
    title: "Plan weekend trip",
    description: "Finalize destination and book accommodations.",
    priority: "low",
    dueDate: "2024-11-18",
    completed: false,
    category: "Leisure",
  },
  {
    id: 4,
    title: "Prepare presentation for meeting",
    description: "Work on slides for the upcoming team meeting.",
    priority: "high",
    dueDate: "2024-11-14",
    completed: false,
    category: "Work",
  },
  {
    id: 5,
    title: "Clean the house",
    description: "Dust, vacuum, and organize the living room and kitchen.",
    priority: "medium",
    dueDate: "2024-11-16",
    completed: true,
    category: "Personal",
  },
  {
    id: 6,
    title: "Write blog post",
    description: "Draft and publish a blog post on JavaScript frameworks.",
    priority: "low",
    dueDate: "2024-11-21",
    completed: false,
    category: "Hobby",
  },
  {
    id: 7,
    title: "Car maintenance",
    description: "Take the car for an oil change and general service.",
    priority: "medium",
    dueDate: "2024-11-17",
    completed: false,
    category: "Personal",
  },
  {
    id: 8,
    title: "Organize files",
    description: "Sort and organize documents on the laptop.",
    priority: "low",
    dueDate: "2024-11-19",
    completed: true,
    category: "Work",
  },
  {
    id: 9,
    title: "Schedule doctor’s appointment",
    description: "Book an appointment for an annual health check-up.",
    priority: "high",
    dueDate: "2024-11-16",
    completed: false,
    category: "Health",
  },
  {
    id: 10,
    title: "Birthday gift shopping",
    description: "Find and buy a gift for John’s birthday.",
    priority: "medium",
    dueDate: "2024-11-18",
    completed: false,
    category: "Personal",
  },
];

export default tasks;
